CREATE TABLE apps (
	id INT KEY AUTO_INCREMENT NOT NULL,
	name VARCHAR(255) NOT NULL,
	google_username VARCHAR(255) UNIQUE NOT NULL,
	google_password VARCHAR(255) UNIQUE NOT NULL,
	ios_username VARCHAR(255) UNIQUE NOT NULL,
	ios_password VARCHAR(255) UNIQUE NOT NULL,
	description VARCHAR(255) NOT NULL,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE devices (
	id INT KEY AUTO_INCREMENT NOT NULL,
	name VARCHAR(255),
	uid VARCHAR(255) UNIQUE,
	appid VARCHAR(255) UNIQUE,
	lang VARCHAR(50) NOT NULL,
	os VARCHAR(50) NOT NULL,
	app_id INTEGER NOT NULL,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    INDEX(uid, os, appid, lang),

	FOREIGN KEY(app_id)
		REFERENCES apps(id)
		ON DELETE CASCADE
);

CREATE TABLE payments (
	id INT KEY AUTO_INCREMENT NOT NULL,
	receipt VARCHAR(255) NOT NULL,
	status VARCHAR(50) NOT NULL,
	device_id INT NOT NULL,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,


	INDEX(receipt, status, device_id),

	FOREIGN KEY(device_id)
			REFERENCES devices(id)
			ON DELETE CASCADE

);

CREATE TABLE subscriptions (
	id INT KEY AUTO_INCREMENT NOT NULL,
	expires_on TIMESTAMP NOT NULL,
	expired bool,
	device_id INT NOT NULL,
	payment_id INT NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,


	INDEX(expires_on, expired, payment_id, device_id),

		FOREIGN KEY(device_id)
			REFERENCES devices(id)
			ON DELETE CASCADE,
        FOREIGN KEY(payment_id)
			REFERENCES payments(id)
			ON DELETE CASCADE
);
